### PR TITLE
fix(cli): unable to import types with all-caps TLAs

### LINKED ISSUE #209: python: unable to import network.aws.crossplane.io/vpc
### Description of the bug:

When trying to import the `network.aws.crossplane.io/vpc` CRD in python, I am getting the following error:

```
network.aws.crossplane.io/vpc
NOTE: Temp directory retained due to an error: /var/folders/n2/6v4_tbz97ws0h4bn5gbyvzb0m8vcjb/T/temp-aqFEwo
Error: jsii compilation failed with non-zero exit code: 1
  | [2020-05-26T21:36:32.591] [ERROR] jsii/compiler - Type model errors prevented the JSII assembly from being created
  | error TS0: Type names must use PascalCase: VPC
  +----------------------------------------------------------------------------------
  | Command: /Users/benisrae/.nvm/versions/node/v10.19.0/lib/node_modules/cdk8s-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/n2/6v4_tbz97ws0h4bn5gbyvzb0m8vcjb/T/temp-aqFEwo
  +----------------------------------------------------------------------------------
    at newError (/Users/benisrae/.nvm/versions/node/v10.19.0/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.child.once.code (/Users/benisrae/.nvm/versions/node/v10.19.0/lib/node_modules/cdk8s-cli/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by eladb**
jsii requires that class names will not be all-caps. This means that a class name like `VPC` is not allowed. To address this, we convert all TLAs to pascal case (i.e. `Vpc`).

Add a unit test for type name normalization.

Fixes #209

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

File: packages/cdk8s-cli/lib/import/type-generator.ts [hunk 1]
```diff
@@ -348,22 +348,26 @@ export class TypeGenerator {
   }
 }
 
+/**
+ * Convert all-caps acronyms (e.g. "VPC", "FooBARZooFIGoo") to pascal case (e.g. "Vpc", "FooBarZooFiGoo").
+ *
+ * @internal exported for tests
+ */
+export function normalizeTypeName(typeName: string) {
```
Comment (iliapolo) [inline packages/cdk8s-cli/lib/import/type-generator.ts:356]: Why did the old implementation only normalize types that start with `I`? This seems like a pretty major behavior change that i'd like to understand the reasoning behind.

Comment (eladb) [reply packages/cdk8s-cli/lib/import/type-generator.ts:356]: Originally I only took care of types that started with `IABCFoo` so that jsii won’t confuse with interfaces, but I’ve realized we should convert everything.

Thanks for caring!

Comment (iliapolo) [reply packages/cdk8s-cli/lib/import/type-generator.ts:356]: Yeah that seems like a better approach 👍
